// config.ts
export const base_url = import.meta.env.VITE_BASE_URL;
export const site_base_url = import.meta.env.VITE_SITE_BASE_URL;

export const calc_form_data = {
    base_url: base_url,
    site_base_url: site_base_url,

    call_back_ep: import.meta.env.VITE_CALL_BACK_EP,

    wp_ajax_url: import.meta.env.VITE_WP_AJAX_URL,
    wp_calc_api: import.meta.env.VITE_WP_CALC_API,

    images_folder: import.meta.env.VITE_IMAGES_FOLDER,

    usr_id: "4f6f466dad8736ac8e3f0ed368ceddc245",
    usr_ip: "254.128.25.29",
    key_ls_name: "form_data_001",
    permission_to_save_data_into_ls: false,
    time_sec_to_keep_def_markers_in_ls: 600,
    osrm_token: "521939eca670",
    request_token: "521939eca670",
    origin_city_default: {
        name: "",
        lat: "",
        lng: "",
    },
    destination_city_default: {
        name: "",
        lat: "",
        lng: "",
    },
};

export const calc_options = {
    step_items: [
        { num: 1, title: "Step 1", description: "Location" },
        { num: 2, title: "Step 2", description: "Load Information" },
        { num: 3, title: "Step 3", description: "Pricing" },
        { num: 4, title: "Step 4", description: "Book a Truck" },
    ],
    first_step_number: 1,
    choose_location: "Сhoose location",
    err_location: "Fill in the correct location name",
    step_1_secondary_text: "Enter origin city to see vehicles in your area",
    origin: "Origin",
    destination: "Destination",
    select_truck_type: "Need a specific truck type?",
    step_1_next_step: "Next Step",
    truck_amount_tmpl: "There are $$ trucks",
    truck_amount_popup_tmpl: "There are $$ trucks in this area",
    truck_amount_one_tmpl: "There is $$ truck",
    truck_types: [
        { title: "Cargo van", value: "Cargo van", img: "cargo-van.png", dimension: "Up to 3 pallets / 3,500 lbs" },
        { title: "Box truck", value: "Box truck", img: "box-truck.png", dimension: "Up to 4-6 pallets / 3,500 lbs" },
        { title: "Straight truck", value: "Straight truck", img: "straight-truck.png", dimension: "Up to 7-14 pallets / 9000 lbs" },
    ],
    trucks_on_the_first_map_limit: 3000,
    truck_type_error_text: "Please select some type of track",
    truck_distance_html: "The distance between <strong>{origin}</strong> and <strong>{destination}</strong> is <strong>{distance}</strong> miles.",
    please_wait: "Please wait,<br/>loading data",

    step_2_title: "Enter your load information",
    pieces: "Pieces / Pallets",
    weight: "Weight",
    weight_data: 100,
    weight_step: 100,
    lbs: "lbs",
    kg: "kg",
    dimensions: "What are your load parameters",
    dimensions_mask: "Width: --″, Height --″, Depth: --″",
    step_2_next_step: "Next Step",
    step_2_back: "Back",
    step_2_pickup_items: ["ASAP", "Later"],
    asap_radius: 70,
    later_radius: 200,
    step_2_pickup_items_descriptions: ["Today/Tomorrow", "In 2 days or more"],
    step_2_pickup_block_title: "When do you need it picked up?",
    step_2_special_instructions_title: "Special Instructions",
    step_2_special_instructions_placeholder: "Special Instructions: E.G., Airport pick up, controlled, equipment, or truck requirements",

    step_3_title: "Our offers for you",
    step_3_note_text: "Prices are provided based on historical data for a specific vehicle time and lane. Actual price may vary depending on market conditions, urgency, special requirements or a need for additional equipment. Please click book your load / request a call back to get a custom quote for your load.",
    edit: "Edit",
    delivered_by: "Delivered By",
    estimated: "Transit time depends on the distance. We can go as fast as 1000 miles per day.",
    you_can_call_us: "Call us for a custom price <a href='tel:470-905-3457'>(470) 905-3457</a>",
    daily_limit: "Looks like you’ve reached your daily limit for quotes. <br />Please call us for a custom price <a href='tel:470-905-3457'>(470) 905-3457</a>",
    get_a_quote_btn: "Book a Truck",
    box_truck: "Box truck",
    cargo_van: "Cargo van",
    straight_truck: "Straight truck",
    step_3_back: "Back",
    distance_tmpl: "$$ miles",
    call_us_phone_href: "tel:470-905-3457",
    request_a_call_back: " Request a call back",
    overweight_info: "This load is too heavy for a ",
    overweight_info_additional: ' <a href="tel:470-905-3457">to find the right truck for you.</a>',
    phone_number: { href: "tel:470-905-3457", text: "(470) 905-3457" },

    step_4_title: "Enter your information to receive a personalized quote within 15 minutes",
    form_heading: "Enter your quote information",
    form_calc_name: "Transportation Data",
    form_contact_name: "Contact Information",
    form_notes_name: "Notes",
    miles_ph: "Miles",
    name_ph: "Name",
    email_ph: "Email",
    phone_ph: "Phone",
    company_name: "Company Name",
    company_type: "Company type",
    notes: "Notes",
    call_me_btn: "Send Request",
    call_reset_btn: "Reset",
    step_4_back: "Back",
    company_type_items: ["Shipper", "Broker", "Manufacturer", "Freight Agent", "Warehouse", "Forwarder"],
    company_type_required_error: "This checkbox group is required",
    privacy_policy_html: 'We respect your privacy and process your data exclusively in accordance with our <a href="/privacy-policy/" target="_blank">Privacy Policy</a>.',
    thank_you_text: "<p>Your request has been sent! We will contact you within 15 minutes.</p>",
    thank_you_btn: "Go to Home Page",
    tab_locations: "1. Locations",
    tab_dimensions: "2. Dimensions",
    tab_rates: "3. Rates",
    trucks_on_the_map_limit: 200,
    trucks_on_the_map_distance_limit: 80,
};
